name       : aisleriot
version    : 3.22.9
release    : 17
source     :
    - https://download.gnome.org/sources/aisleriot/3.22/aisleriot-3.22.9.tar.xz : 51f2ffe4dd4f23349b033fd87aab7bf433641285719503dd7e52b2c25982ed7b
license    :
    - LGPL-3.0-or-later
    - GPL-3.0-or-later
    - GFDL-1.1
component  : games.card
summary    : Gnome Aisleriot Card Game
description: |
    Gnome Aisleriot Card Game
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(guile-2.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(librsvg-2.0)
    - desktop-file-utils
    - itstool
    - pysolfc
    - pysolfc-cardsets
rundeps    :
    - pysolfc
    - pysolfc-cardsets
clang      : no
setup      : |
    %configure --with-card-theme-formats=svg --with-pysol-card-theme-path=/usr/share/PySolFC/
build      : |
    %make
install    : |
    %make_install
