name       : aisleriot
version    : 3.22.4
release    : 12
source     :
    - https://download.gnome.org/sources/aisleriot/3.22/aisleriot-3.22.4.tar.xz : fe8dee3ad771ab778d37740a26410778aa5c61e8eb75dd42b9a5e5719c6e34fb
license    :
    - LGPL-3.0
    - GPL-3.0
    - GFDL-1.1
component  : games.card
summary    : Gnome Aisleriot Card Game
description: |
    Gnome Aisleriot Card Game
builddeps  :
    - pkgconfig(guile-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(gconf-2.0)
    - pkgconfig(bdw-gc)
    - desktop-file-utils
    - itstool
    - pysolfc
    - pysolfc-cardsets
rundeps    :
    - pysolfc
    - pysolfc-cardsets
clang      : no
setup      : |
    %configure --with-card-theme-formats=pysol --with-pysol-card-theme-path=/usr/share/PySolFC/
build      : |
    %make
install    : |
    %make_install
