name       : aisleriot
version    : 3.16.2
release    : 2
source     :
    - http://ftp.gnome.org/pub/gnome/sources/aisleriot/3.16/aisleriot-3.16.2.tar.xz : f483fd743734575dc5ab053702d78c3521ccd5c2e5701f4e9af1681fc46bcc66
license    :
    - LGPL-3.0
    - GPL-3.0
    - GFDL-1.1
summary    : Gnome Aisleriot Card Game
description: |
    Gnome Aisleriot Card Game
builddeps  :
    - pkgconfig(guile-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(gconf-2.0)
    - pkgconfig(bdw-gc)
    - desktop-file-utils
    - itstool
    - pysolfc
    - pysolfc-cardsets
clang      : no
setup      : |
    %configure --with-card-theme-formats=pysol --with-pysol-card-theme-path=/usr/share/PySolFC/
build      : |
    %make
install    : |
    %make_install
